### ISSUE TITLE
corner.quantiles imports in lenstronomy

### ISSUE THREAD

**Issue by sibirrer** [AlexandreAdam/rxj1131#1]
Hi Alexandre,
I was just glancing through your td_notebook using lenstronomy (sorry, just showed up in the packages using lenstronomy and I clicked on it :) ).
I see an error in the import of
`from corner.corner import quantile`
The corner library has recently been updated/refactored such that the new import statement is
`from corner import quantile`
The latest lenstronomy version has been updated to match with the latest corner version. So if you update your fork with the latest main branch version, this should be fixed.

I hope this helps. Let me know if you have questions.

Cheers,
Simon

and thanks for using lenstronomy :)

**Comment by sibirrer** [comment]
ah, you would actually not need to fork the repo, but only upgrade the installation to the latest PyPi version 1.8.1. Sorry, had thought you forked the repo. But forking does work too. You need to go a bit more in the weeds of GitHub but you have full control over the source code you are using.

**Comment by AlexandreAdam** [comment]
Hi Simon!

Yeah I just realized that I was on an earlier version and upgraded it (both
on lentronomy and corner). But wow thank you I was working through this
problem just now and you messaged me as I realized what was the issue!

I updated my branch to the latest version and it works now thank you. I am
having another bug though, which occurs in the middle of the Fitting
Sequence while doing the MCMC. I am not sure what is the problem yet so I
might open an Issue if that works with you.

Cheers!

Alexandre

**Comment by sibirrer** [comment]
Feel free, if you can't resolve the issue with some googling and error message reading, to open an issue on the lenstronomy repo, or write me an email. You could also join the lenstronomy Slack channel and either post there your issue on a public channel or through private messages. Whatever you prefer. I guess I can close this issue here.

Cheers,
Simon

**Comment by AlexandreAdam** [comment]
Hi Simon,

I figured out the problem. As it turns out, the SPEP profile hessian method
returns 3 elements instead of 4 when the Einstein radius is negative. This
would throw out an error when passing the output to the single plane
hessian method, which expect the 4 elements of the matrix.

I provided a screenshot of the error. This happened during the MCMC (either
at the beginning of it like in this picture or sometimes in the middle of
it). I don't know if this is an issue or intended behavior. It might be
that I did not provide boundary constraints properly to the
FittingSequence. In any case I am not sure how the Einstein radius turned
out to be negative during the Monte Carlo search.

I can open up a proper issue if this is not a problem on my part.

Best,

Alexandre Adam

**Comment by sibirrer** [comment]
ah, I see. This was an oversight when changing the return argument to 4 entries and the case with unphysical Einstein radius was not considered. The latest commit to lenstronomy main branch should fix it. Thanks for pointing this out! Apparently you were not restricting Einstein radii to be positive definite during the sampling and this was not noticed for most of the users that went that route.
